package com.apollon.webapp.util.sms;

/*
import no.vianett.sms.SmsEventListener;
import no.vianett.sms.Sms;
import no.vianett.sms.SmsEvent;
import no.vianett.sms.component.SmsTransceiver;
import no.vianett.sms.log.SmsScreenLogger;
import no.vianett.sms.event.SmsDeliveredEvent;
import no.vianett.sms.event.SmsSendingFailedEvent;
import no.vianett.sms.event.SmsDeliveryFailedEvent;
 */

public final class SmsVianettSender /*implements SmsEventListener*/ {
	
	/*
    private SmsTransceiver transceiver = null;
    @SuppressWarnings("unused")
	private Object link = null; // Just to keep this object alive.
    private int counter = 0;
 
    public SmsVianettSender(){
        this.link = this; // Keeps this object alive.
        this.transceiver = SmsTransceiver.getInstance(); // Get the transceiver object.
 
        // Initialize transceiver.
        String smsHost = "cpa.vianett.no";
        String smsPort = "31337";
        String smsUsername = "matteo.manili@gmail.com";
        String smsPassword = "giulietta01";
        this.transceiver.initialize( smsHost, Integer.parseInt( smsPort ), smsUsername, smsPassword, new SmsScreenLogger() );
 
        this.transceiver.addSmsEventListener( this ); // Registrer this class as listener for SMS events.
        
        // Send message
        Sms sms = new Sms();
        
        //sms.setCampaignId(345455);
        //sms.setOperator(1);
        //sms.set
        
        
        sms.setId( ++this.counter );
        sms.setReplyPath( 100 );
        sms.setSender( "1963" ); // Set the sender number. //340047
        sms.setMessage( "hello word?" );
        sms.setRecipient( "393289126869" ); // The recipients phone number.
        //sms.setRecipient( "584264634139" ); // The recipients phone number.
        this.transceiver.send( sms );
    }
 
    // Just make new instance of this class.
    public static void main( String[] args ){ new SmsVianettSender(); }
 

    public void eventHappened( SmsEvent event )
    {
        if( event instanceof SmsDeliveredEvent )
        {
            System.out.println( "Sms delivered." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsSendingFailedEvent )
        {
            System.out.println( "Sms sending failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Return code : " + ( ( SmsSendingFailedEvent ) event ).getReturnCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsDeliveryFailedEvent )
        {
            System.out.println( "Sms delivery failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Error code : " + ( ( SmsDeliveryFailedEvent ) event ).getErrorCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
    }
    */
    
}